[package]
name = "sysbus"
version = "2.2.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
license = "Mulan PSL v2"
description = "Emulate system bus"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
kvm-ioctls = "0.13.0"
vmm-sys-util = "0.11.1"
acpi = { path = "../acpi" }
address_space = { path = "../address_space" }
hypervisor = { path = "../hypervisor" }
util = {path = "../util"}
